fix(ci): add missing preview to match the build and push conditions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,6 +2,10 @@ name: release
 
 on:
   workflow_dispatch:
+    inputs:
+      preview:
+        description: 'Preview tag if not empty. Needs to be in format vX.Y.Z-preview.X'
+        type: string
   pull_request:
     types: [closed]
     branches:
@@ -23,8 +27,17 @@ jobs:
       - name: Get version
         id: release_info
         run: |
-          cargo install cargo-get
-          echo "tag_name=v$(cargo get workspace.package.version)" >> $GITHUB_OUTPUT
+          if [[ "${{ github.event.inputs.preview || 'false' }}" != "false" ]]; then
+            # check if valid
+            if [[ ! "${{ github.event.inputs.preview }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+$ ]]; then
+              echo "Invalid preview tag format. Needs to be in format vX.Y.Z-preview.X"
+              exit 1
+            fi
+            echo "tag_name=${{ github.event.inputs.preview }}" >> $GITHUB_OUTPUT
+          else
+            cargo install cargo-get
+            echo "tag_name=v$(cargo get workspace.package.version)" >> $GITHUB_OUTPUT
+          fi
 
   release:
     name: ${{ matrix.job.target }} (${{ matrix.job.os }})
